"""empty message

Revision ID: 6070b11acb60
Revises: 
Create Date: 2022-08-18 14:58:34.536914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6070b11acb60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artistgenre')
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    op.create_table('artistgenre',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='artistgenre_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='artistgenre_genre_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id', name='artistgenre_pkey')
    )
    # ### end Alembic commands ###
